spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost:5434/acl
  flyway:
    baseline-on-migrate: true
    baseline-version: 0

logging.level.org.hibernate.orm.jdbc.bind: trace
logging.level.sql: debug